### ISSUE TITLE
return subresources not in raw json

### ISSUE THREAD

**Issue by stubbi** [swarms/python-sdk#1]
```from pprint import pprint
from swarms.sdk import services

config = lambda: None
config.base_url = 'https://api.swarms.tech/'
config.username = '####'
config.password = '#####'

campaigns, jobs, tasks, results = services.get(config)

c = campaigns.get(1116)
js = campaigns.get_jobs(c)
```

returns the jobs (js) as the raw json. It would be cool if we could have them as the job resource. Didn't check but would expect the same behaviour for tasks of a job.

**Comment by tasuki** [comment]
I can't reproduce this. Also can't see any historical version which would behave this way.

My local experiment:
```
from sdk import services       
                               
config = lambda: None          
config.base_url = 'http://localhost:9040/'
config.username = 'ash.ketchum@alabastia.pkm'
config.password = 'pickachu'   

campaigns, jobs, tasks, results = services.get(config)

c = campaigns.get(12)          
print(c["name"])               
js = campaigns.get_jobs(c)
for job in js["jobs"]:         
    print(job["name"])
```

Results in:
```
My zen campaign
Solve koans
Meditate
```

Please note that the SDK doesn't have "resources" as such - for sake of simplicity everything is decoded into lists & dicts.

**Comment by stubbi** [comment]
Ah, yes. But's that's exactly what I mean. You are accessing the jobs as a dict. and the problem is that there would also be pages which are not so easy to deal with if I remember correctly, right?

**Comment by tasuki** [comment]
Stubbi, I'm not sure I understand. So is this about paging? Or about something else entirely?

**Comment by stubbi** [comment]
both. I mean. I can do something like `jobs.getAll` and `jobs.getPages`. I would like to do the same for `campaigns.getAllJobs` and `campaigns.getJobPages` with the very same output format

**Comment by tasuki** [comment]
can we close this? :smiley:

**Comment by stubbi** [comment]
Sure!
